baseurl: /

collections:
  public:
    output: true
    permalink: /:path
  pages:
    output: true
    permalink: /:path
  products:
    output: true
    permalink: /products/:path

exclude:
  - LICENSE

sass:
  style: compressed
