# Jekyll 
baseurl: ''
exclude:
  - node_modules
  - .gitignore
  - gulpfile.js
  - index.js
  - package-lock.json
  - package.json
  - README.md
  - webpack.config.js

# vars
title: ООО "ДЕ-ПА"
description: ...
authors: PavelGalanin2001
