baseurl: ''
source: ./src
destination: dist
collections:
    public:
        output: true
        permalink: /:path
    pages:
        output: true
        permalink: /:path/
exclude:
    - index.js
    - index.sass
