# Jekyll 
baseurl: ''
exclude:
  - node_modules
  - .gitignore
  - gulpfile.js
  - index.js
  - package-lock.json
  - package.json
  - README.md
  - webpack.config.js

# vars
title: ООО "ДЕ-ПА"
description: Общество с ограниченной ответственностью «ДЕ-ПА» (УНП 291477952) является эксклюзивным дистрибьютером турецких производителей электротехнической, светотехнической и кабельно-проводниковой продукции, таких как «DE-PA ELECTRIC», «MONO ELECTRIC», «HISAR ELECTRIC», «RECBER KABLO», «EBION KABLO» которые уже более 35 лет являются известнейшими производителями и поставщиками электроустановочных изделий, светильников, кабельной продукции, наконечников не только в Турции, но и в России, Казахстане, Украине, Европе, Ираке, Иране, Алжире и др. странах мира.
authors: PavelGalanin2001
