baseurl: /

collections:
  public:
    output: true
    permalink: /:path
  favicons:
    output: true
    permalink: /:path
  pages:
    output: true
    permalink: /:path
  products:
    output: true
    permalink: /products/:path
  ozon_products:
    output: true
    permalink: /ozon-products/:path

exclude:
  - _cron
  - LICENSE

sass:
  style: compressed
