main-menu:

  - title: Главная
    url: /

  - title: О нас
    url: /about-us

  - title: Каталоги
    url: /katalogs

  - title: Продукция
    url: /products

  - title: Сертификаты
    url: /certificates

  - title: Прайсы
    url: /prices

  - title: Контакты
    url: /contacts